package tokens

import (
	"sync"
)

// NameToken represents a name object in a PDF document. A name is an atomic symbol
// uniquely defined by a sequence of characters. Names are used to identify dictionary
// keys and other elements of a PDF document. Each unique string maps to exactly one
// NameToken instance (interning).
type NameToken struct {
	data string
}

var _ Token = (*NameToken)(nil)
var _ DataToken[string] = (*NameToken)(nil)

var nameMu sync.Mutex
var nameMap = make(map[string]*NameToken, 1024)

// Create returns a NameToken for the given name string. If a token with that
// name already exists, the existing instance is returned (interning).
func Create(name string) *NameToken {
	nameMu.Lock()
	defer nameMu.Unlock()

	if token, ok := nameMap[name]; ok {
		return token
	}

	token := &NameToken{data: name}
	nameMap[name] = token
	return token
}

// Data returns the string representation of the name.
func (n *NameToken) Data() string {
	return n.data
}

// Equals reports whether other is a NameToken with the same data value.
func (n *NameToken) Equals(other Token) bool {
	o, ok := other.(*NameToken)
	if !ok || o == nil {
		return false
	}
	return n.data == o.data
}

// String returns the string representation of the name token prefixed with '/'.
func (n *NameToken) String() string {
	if n == nil {
		return ""
	}
	return "/" + n.data
}

// MustCreate creates a NameToken for the given name. It is equivalent to Create
// but without error return, used for package-level constant initialization.
func MustCreate(name string) *NameToken {
	return Create(name)
}

// A
var (
	A                        = MustCreate("A")
	Aa                       = MustCreate("AA")
	AcroForm                 = MustCreate("AcroForm")
	ActualText               = MustCreate("ActualText")
	AdbePkcs7Detached        = MustCreate("adbe.pkcs7.detached")
	AdbePkcs7Sha1            = MustCreate("adbe.pkcs7.sha1")
	AdbeX509RsaSha1          = MustCreate("adbe.x509.rsa_sha1")
	AdobePpklite             = MustCreate("Adobe.PPKLite")
	Aesv2                    = MustCreate("AESV2")
	Aesv3                    = MustCreate("AESV3")
	After                    = MustCreate("After")
	Ais                      = MustCreate("AIS")
	Alt                      = MustCreate("Alt")
	Alpha                    = MustCreate("Alpha")
	Alternate                = MustCreate("Alternate")
	Annotation3D             = MustCreate("3D")
	Annot                    = MustCreate("Annot")
	Annots                   = MustCreate("Annots")
	AntiAlias                = MustCreate("AntiAlias")
	Ap                       = MustCreate("AP")
	ApRef                    = MustCreate("APRef")
	App                      = MustCreate("App")
	ArtBox                   = MustCreate("ArtBox")
	Artifact                 = MustCreate("Artifact")
	As                       = MustCreate("AS")
	Ascent                   = MustCreate("Ascent")
	AsciiHexDecode           = MustCreate("ASCIIHexDecode")
	AsciiHexDecodeAbbreviation = MustCreate("AHx")
	Ascii85Decode            = MustCreate("ASCII85Decode")
	Ascii85DecodeAbbreviation  = MustCreate("A85")
	Attached                 = MustCreate("Attached")
	AuthEvent                = MustCreate("AuthEvent")
	Author                   = MustCreate("Author")
	AvgWidth                 = MustCreate("AvgWidth")
)

// B
var (
	B                         = MustCreate("B")
	Background                = MustCreate("Background")
	BaseEncoding              = MustCreate("BaseEncoding")
	BaseFont                  = MustCreate("BaseFont")
	BaseState                 = MustCreate("BaseState")
	Bbox                      = MustCreate("BBox")
	Bc                        = MustCreate("BC")
	Be                        = MustCreate("BE")
	Before                    = MustCreate("Before")
	Bg                        = MustCreate("BG")
	BitsPerComponent          = MustCreate("BitsPerComponent")
	BitsPerCoordinate         = MustCreate("BitsPerCoordinate")
	BitsPerFlag               = MustCreate("BitsPerFlag")
	BitsPerSample             = MustCreate("BitsPerSample")
	BlackIs1                  = MustCreate("BlackIs1")
	BlackPoint                = MustCreate("BlackPoint")
	BleedBox                  = MustCreate("BleedBox")
	Bm                        = MustCreate("BM")
	Border                    = MustCreate("Border")
	Bottom                    = MustCreate("Bottom")
	Bounds                    = MustCreate("Bounds")
	Bpc                       = MustCreate("BPC")
	Bs                        = MustCreate("BS")
	Btn                       = MustCreate("Btn")    // Acro form field type for button fields.
	Byterange                 = MustCreate("ByteRange")
)

// C
var (
	C                         = MustCreate("C")
	C0                        = MustCreate("C0")
	C1                        = MustCreate("C1")
	Ca                        = MustCreate("CA")
	CaNs                      = MustCreate("ca")
	Calgray                   = MustCreate("CalGray")
	Calrgb                    = MustCreate("CalRGB")
	Cap                       = MustCreate("Cap")
	CapHeight                 = MustCreate("CapHeight")
	Caret                     = MustCreate("Caret")
	Catalog                   = MustCreate("Catalog")
	CcittfaxDecode            = MustCreate("CCITTFaxDecode")
	CcittfaxDecodeAbbreviation = MustCreate("CCF")
	CenterWindow              = MustCreate("CenterWindow")
	Cf                        = MustCreate("CF")
	Cfm                       = MustCreate("CFM")
	Ch                        = MustCreate("Ch")     // Acro form field type for choice fields.
	CharProcs                 = MustCreate("CharProcs")
	CharSet                   = MustCreate("CharSet")
	CiciSignit                = MustCreate("CICI.SignIt")
	CidFontType0              = MustCreate("CIDFontType0")
	CidFontType0C             = MustCreate("CIDFontType0C")
	CidFontType2              = MustCreate("CIDFontType2")
	CidInit                   = MustCreate("CIDInit")
	CidToGidMap               = MustCreate("CIDToGIDMap")
	CidSet                    = MustCreate("CIDSet")
	CidSystemInfo             = MustCreate("CIDSystemInfo")
	Circle                    = MustCreate("Circle")
	Cl                        = MustCreate("CL")
	ClrF                      = MustCreate("ClrF")
	ClrFf                     = MustCreate("ClrFf")
	Cmap                      = MustCreate("CMap")
	Cmapname                  = MustCreate("CMapName")
	CmapType                  = MustCreate("CMapType")
	Cmyk                      = MustCreate("CMYK")
	Co                        = MustCreate("CO")
	ColorBurn                 = MustCreate("ColorBurn")
	ColorDodge                = MustCreate("ColorDodge")
	Colorants                 = MustCreate("Colorants")
	Colors                    = MustCreate("Colors")
	ColorSpace                = MustCreate("ColorSpace")
	Columns                   = MustCreate("Columns")
	Compatible                = MustCreate("Compatible")
	Components                = MustCreate("Components")
	ContactInfo               = MustCreate("ContactInfo")
	Contents                  = MustCreate("Contents")
	Coords                    = MustCreate("Coords")
	Count                     = MustCreate("Count")
	Cp                        = MustCreate("CP")
	CreationDate              = MustCreate("CreationDate")
	Creator                   = MustCreate("Creator")
	CropBox                   = MustCreate("CropBox")
	Crypt                     = MustCreate("Crypt")
	CryptAlgorithm            = MustCreate("CryptAlgorithm")
	CryptFilter               = MustCreate("CryptFilter")
	Cs                        = MustCreate("CS")
)

// D
var (
	D                         = MustCreate("D")
	Da                        = MustCreate("DA")
	Darken                    = MustCreate("Darken")
	Date                      = MustCreate("Date")
	DctDecode                 = MustCreate("DCTDecode")
	DctDecodeAbbreviation     = MustCreate("DCT")
	Decode                    = MustCreate("Decode")
	DecodeParms               = MustCreate("DecodeParms")
	Default                   = MustCreate("default")
	DefaultCmyk               = MustCreate("DefaultCMYK")
	DefaultGray               = MustCreate("DefaultGray")
	DefaultRgb                = MustCreate("DefaultRGB")
	Desc                      = MustCreate("Desc")
	DescendantFonts           = MustCreate("DescendantFonts")
	Descent                   = MustCreate("Descent")
	Dest                      = MustCreate("Dest")
	DestOutputProfile         = MustCreate("DestOutputProfile")
	Dests                     = MustCreate("Dests")
	Devicecmyk                = MustCreate("DeviceCMYK")
	Devicegray                = MustCreate("DeviceGray")
	Devicen                   = MustCreate("DeviceN")
	Devicergb                 = MustCreate("DeviceRGB")
	Di                        = MustCreate("Di")
	Difference                = MustCreate("Difference")
	Differences               = MustCreate("Differences")
	DigestMethod              = MustCreate("DigestMethod")
	DigestRipemd160           = MustCreate("RIPEMD160")
	DigestSha1                = MustCreate("SHA1")
	DigestSha256              = MustCreate("SHA256")
	DigestSha384              = MustCreate("SHA384")
	DigestSha512              = MustCreate("SHA512")
	Direction                 = MustCreate("Direction")
	DisplayDocTitle           = MustCreate("DisplayDocTitle")
	Dl                        = MustCreate("DL")
	Dm                        = MustCreate("Dm")
	Doc                       = MustCreate("Doc")
	DocOpen                   = MustCreate("DocOpen")
	DocChecksum               = MustCreate("DocChecksum")
	DocTimeStamp              = MustCreate("DocTimeStamp")
	Docmdp                    = MustCreate("DocMDP")
	Domain                    = MustCreate("Domain")
	Dos                       = MustCreate("DOS")
	Dp                        = MustCreate("DP")
	Dr                        = MustCreate("DR")
	Ds                        = MustCreate("DS")
	Duplex                    = MustCreate("Duplex")
	Dur                       = MustCreate("Dur")
	Dv                        = MustCreate("DV")
	Dw                        = MustCreate("DW")
	Dw2                       = MustCreate("DW2")
)

// E
var (
	E                         = MustCreate("E")
	EarlyChange               = MustCreate("EarlyChange")
	Ef                        = MustCreate("EF")
	EfOpen                    = MustCreate("EFOpen")
	EmbeddedFdfs              = MustCreate("EmbeddedFDFs")
	EmbeddedFiles             = MustCreate("EmbeddedFiles")
	Empty                     = MustCreate("")
	Encode                    = MustCreate("Encode")
	EncodedByteAlign          = MustCreate("EncodedByteAlign")
	Encoding                  = MustCreate("Encoding")
	Encoding90MsRksjH         = MustCreate("90ms-RKSJ-H")
	Encoding90MsRksjV         = MustCreate("90ms-RKSJ-V")
	EncodingEtenB5H           = MustCreate("ETen-B5-H")
	EncodingEtenB5V           = MustCreate("ETen-B5-V")
	Encrypt                   = MustCreate("Encrypt")
	EncryptMetaData           = MustCreate("EncryptMetadata")
	EndOfLine                 = MustCreate("EndOfLine")
	EntrustPpkef              = MustCreate("Entrust.PPKEF")
	Exclusion                 = MustCreate("Exclusion")
	ExtGState                 = MustCreate("ExtGState")
	Extend                    = MustCreate("Extend")
	Extends                   = MustCreate("Extends")
)

// F
var (
	F                         = MustCreate("F")
	FDecodeParms              = MustCreate("FDecodeParms")
	FFilter                   = MustCreate("FFilter")
	Fb                        = MustCreate("FB")
	Fdf                       = MustCreate("FDF")
	Ff                        = MustCreate("Ff")
	Fields                    = MustCreate("Fields")
	FileAttachment            = MustCreate("FileAttachment")
	Filespec                  = MustCreate("Filespec")
	Filter                    = MustCreate("Filter")
	First                     = MustCreate("First")
	FirstChar                 = MustCreate("FirstChar")
	Fit                       = MustCreate("Fit")
	FitB                      = MustCreate("FitB")
	FitBH                     = MustCreate("FitBH")
	FitBV                     = MustCreate("FitBV")
	FitH                      = MustCreate("FitH")
	FitR                      = MustCreate("FitR")
	FitV                      = MustCreate("FitV")
	FitWindow                 = MustCreate("FitWindow")
	Fl                        = MustCreate("FL")
	Flags                     = MustCreate("Flags")
	FlateDecode               = MustCreate("FlateDecode")
	FlateDecodeAbbreviation   = MustCreate("Fl")
	Font                      = MustCreate("Font")
	FontBbox                  = MustCreate("FontBBox")
	FontDescriptor            = MustCreate("FontDescriptor")
	FontFamily                = MustCreate("FontFamily")
	FontFile                  = MustCreate("FontFile")
	FontFile2                 = MustCreate("FontFile2")
	FontFile3                 = MustCreate("FontFile3")
	FontMatrix                = MustCreate("FontMatrix")
	FontName                  = MustCreate("FontName")
	FontStretch               = MustCreate("FontStretch")
	FontWeight                = MustCreate("FontWeight")
	Form                      = MustCreate("Form")
	Formtype                  = MustCreate("FormType")
	Frm                       = MustCreate("FRM")
	FreeText                  = MustCreate("FreeText")
	Ft                        = MustCreate("FT")
	Function                  = MustCreate("Function")
	FunctionType              = MustCreate("FunctionType")
	Functions                 = MustCreate("Functions")
)

// G
var (
	G                         = MustCreate("G")
	Gamma                     = MustCreate("Gamma")
	GoTo                      = MustCreate("GoTo")
	GoToE                     = MustCreate("GoToE")
	GoToR                     = MustCreate("GoToR")
	Group                     = MustCreate("Group")
	GtsPdfa1                  = MustCreate("GTS_PDFA1")
)

// H
var (
	H                         = MustCreate("H")
	HardLight                 = MustCreate("HardLight")
	Height                    = MustCreate("Height")
	HideMenubar               = MustCreate("HideMenubar")
	HideToolbar               = MustCreate("HideToolbar")
	HideWindowui              = MustCreate("HideWindowUI")
	Highlight                 = MustCreate("Highlight")
)

// I
var (
	I                         = MustCreate("I")
	Ic                        = MustCreate("IC")
	Iccbased                  = MustCreate("ICCBased")
	Id                        = MustCreate("ID")
	IdTree                    = MustCreate("IDTree")
	Identity                  = MustCreate("Identity")
	IdentityH                 = MustCreate("Identity-H")
	IdentityV                 = MustCreate("Identity-V")
	If                        = MustCreate("IF")
	Im                        = MustCreate("IM")
	Image                     = MustCreate("Image")
	ImageB                    = MustCreate("ImageB")
	ImageC                    = MustCreate("ImageC")
	ImageI                    = MustCreate("ImageI")
	ImageMask                 = MustCreate("ImageMask")
	Index                     = MustCreate("Index")
	Indexed                   = MustCreate("Indexed")
	Info                      = MustCreate("Info")
	Ink                       = MustCreate("Ink")
	Inklist                   = MustCreate("InkList")
	Intent                    = MustCreate("Intent")
	Interpolate               = MustCreate("Interpolate")
	Irt                       = MustCreate("IRT")
	It                        = MustCreate("IT")
	ItalicAngle               = MustCreate("ItalicAngle")
)

// J
var (
	JavaScript                = MustCreate("JavaScript")
	Jbig2Decode               = MustCreate("JBIG2Decode")
	Jbig2Globals              = MustCreate("JBIG2Globals")
	JpxDecode                 = MustCreate("JPXDecode")
	Js                        = MustCreate("JS")
)

// K
var (
	K                         = MustCreate("K")
	Keywords                  = MustCreate("Keywords")
	Kids                      = MustCreate("Kids")
)

// L
var (
	L                         = MustCreate("L")
	Lab                       = MustCreate("Lab")
	Lang                      = MustCreate("Lang")
	Last                      = MustCreate("Last")
	LastChar                  = MustCreate("LastChar")
	LastModified              = MustCreate("LastModified")
	Launch                    = MustCreate("Launch")
	Lc                        = MustCreate("LC")
	Le                        = MustCreate("LE")
	Leading                   = MustCreate("Leading")
	Left                      = MustCreate("Left")
	LegalAttestation          = MustCreate("LegalAttestation")
	Length                    = MustCreate("Length")
	Length1                   = MustCreate("Length1")
	Length2                   = MustCreate("Length2")
	Lighten                   = MustCreate("Lighten")
	Limits                    = MustCreate("Limits")
	Line                      = MustCreate("Line")
	Link                      = MustCreate("Link")
	Lj                        = MustCreate("LJ")
	Ll                        = MustCreate("LL")
	Lle                       = MustCreate("LLE")
	Llo                       = MustCreate("LLO")
	Location                  = MustCreate("Location")
	Luminosity                = MustCreate("Luminosity")
	Lw                        = MustCreate("LW")
	LzwDecode                 = MustCreate("LZWDecode")
	LzwDecodeAbbreviation     = MustCreate("LZW")
)

// M
var (
	M                         = MustCreate("M")
	Mac                       = MustCreate("Mac")
	MacExpertEncoding         = MustCreate("MacExpertEncoding")
	MacRomanEncoding          = MustCreate("MacRomanEncoding")
	Marked                    = MustCreate("Marked")
	MarkInfo                  = MustCreate("MarkInfo")
	Mask                      = MustCreate("Mask")
	Matrix                    = MustCreate("Matrix")
	Matte                     = MustCreate("Matte")
	MaxLen                    = MustCreate("MaxLen")
	MaxWidth                  = MustCreate("MaxWidth")
	Mcid                      = MustCreate("MCID")
	Mdp                       = MustCreate("MDP")
	Measure                   = MustCreate("Measure")
	MediaBox                  = MustCreate("MediaBox")
	Metadata                  = MustCreate("Metadata")
	MissingWidth              = MustCreate("MissingWidth")
	Mix                       = MustCreate("Mix")
	MixingHints               = MustCreate("MixingHints")
	Mk                        = MustCreate("MK")
	Ml                        = MustCreate("ML")
	MmType1                   = MustCreate("MMType1")
	ModDate                   = MustCreate("ModDate")
	Movie                     = MustCreate("Movie")
	Multiply                  = MustCreate("Multiply")
)

// N
var (
	N                         = MustCreate("N")
	Name                      = MustCreate("Name")
	Names                     = MustCreate("Names")
	NeedAppearances           = MustCreate("NeedAppearances")
	Next                      = MustCreate("Next")
	Nm                        = MustCreate("NM")
	NonEfontNoWarn            = MustCreate("NonEFontNoWarn")
	NonFullScreenPageMode     = MustCreate("NonFullScreenPageMode")
	None                      = MustCreate("None")
	Normal                    = MustCreate("Normal")
	Nums                      = MustCreate("Nums")
)

// O
var (
	O                         = MustCreate("O")
	Obj                       = MustCreate("Obj")
	ObjStm                    = MustCreate("ObjStm")
	Oc                        = MustCreate("OC")
	Ocg                       = MustCreate("OCG")
	Ocgs                      = MustCreate("OCGs")
	Ocproperties              = MustCreate("OCProperties")
	Oe                        = MustCreate("OE")
	Off                       = MustCreate("OFF")    // For OCGs, not for Acroform.
	OffAcroform               = MustCreate("Off")    // For Acroform, not for OCGs.
	On                        = MustCreate("ON")
	Op                        = MustCreate("OP")
	OpNs                      = MustCreate("op")
	OpenAction                = MustCreate("OpenAction")
	OpenType                  = MustCreate("OpenType")
	Opm                       = MustCreate("OPM")
	Opt                       = MustCreate("Opt")
	Order                     = MustCreate("Order")
	Ordering                  = MustCreate("Ordering")
	Os                        = MustCreate("OS")
	Outlines                  = MustCreate("Outlines")
	OutputCondition           = MustCreate("OutputCondition")
	OutputConditionIdentifier  = MustCreate("OutputConditionIdentifier")
	OutputIntent              = MustCreate("OutputIntent")
	OutputIntents             = MustCreate("OutputIntents")
	Overlay                   = MustCreate("Overlay")
)

// P
var (
	P                         = MustCreate("P")
	Page                      = MustCreate("Page")
	PageLabels                = MustCreate("PageLabels")
	PageLayout                = MustCreate("PageLayout")
	PageMode                  = MustCreate("PageMode")
	Pages                     = MustCreate("Pages")
	PaintType                 = MustCreate("PaintType")
	Panose                    = MustCreate("Panose")
	Params                    = MustCreate("Params")
	Parent                    = MustCreate("Parent")
	ParentTree                = MustCreate("ParentTree")
	ParentTreeNextKey         = MustCreate("ParentTreeNextKey")
	Pattern                   = MustCreate("Pattern")
	PatternType               = MustCreate("PatternType")
	PdfDocEncoding            = MustCreate("PDFDocEncoding")
	Perms                     = MustCreate("Perms")
	Pg                        = MustCreate("Pg")
	Polygon                   = MustCreate("Polygon")
	PolyLine                  = MustCreate("PolyLine")
	Popup                     = MustCreate("Popup")
	PreRelease                = MustCreate("PreRelease")
	Predictor                 = MustCreate("Predictor")
	Prev                      = MustCreate("Prev")
	PrintArea                 = MustCreate("PrintArea")
	PrintClip                 = MustCreate("PrintClip")
	PrintScaling              = MustCreate("PrintScaling")
	PrinterMark               = MustCreate("PrinterMark")
	ProcSet                   = MustCreate("ProcSet")
	Process                   = MustCreate("Process")
	Producer                  = MustCreate("Producer")
	PropBuild                 = MustCreate("Prop_Build")
	Properties                = MustCreate("Properties")
	Ps                        = MustCreate("PS")
	PubSec                    = MustCreate("PubSec")
)

// Q
var (
	Q                         = MustCreate("Q")
	Quadpoints                = MustCreate("QuadPoints")
)

// R
var (
	R                         = MustCreate("R")
	Range                     = MustCreate("Range")
	Rc                        = MustCreate("RC")
	Rd                        = MustCreate("RD")
	Reason                    = MustCreate("Reason")
	Reasons                   = MustCreate("Reasons")
	Repeat                    = MustCreate("Repeat")
	Recipients                = MustCreate("Recipients")
	Rect                      = MustCreate("Rect")
	Registry                  = MustCreate("Registry")
	RegistryName              = MustCreate("RegistryName")
	Rename                    = MustCreate("Rename")
	Resources                 = MustCreate("Resources")
	Rgb                       = MustCreate("RGB")
	Ri                        = MustCreate("RI")
	Right                     = MustCreate("Right")
	RoleMap                   = MustCreate("RoleMap")
	Root                      = MustCreate("Root")
	Rotate                    = MustCreate("Rotate")
	Rows                      = MustCreate("Rows")
	RunLengthDecode           = MustCreate("RunLengthDecode")
	RunLengthDecodeAbbreviation = MustCreate("RL")
	Rv                        = MustCreate("RV")
)

// S
var (
	S                         = MustCreate("S")
	Sa                        = MustCreate("SA")
	Screen                    = MustCreate("Screen")
	Se                        = MustCreate("SE")
	Separation                = MustCreate("Separation")
	SetF                      = MustCreate("SetF")
	SetFf                     = MustCreate("SetFf")
	Shading                   = MustCreate("Shading")
	ShadingType               = MustCreate("ShadingType")
	Sig                       = MustCreate("Sig")
	SigFlags                  = MustCreate("SigFlags")
	Size                      = MustCreate("Size")
	Sm                        = MustCreate("SM")
	Smask                     = MustCreate("SMask")
	SoftLight                 = MustCreate("SoftLight")
	Sound                     = MustCreate("Sound")
	Square                    = MustCreate("Square")
	Squiggly                  = MustCreate("Squiggly")
	Ss                        = MustCreate("SS")
	St                        = MustCreate("St")
	Stamp                     = MustCreate("Stamp")
	StandardEncoding          = MustCreate("StandardEncoding")
	SymbolEncoding            = MustCreate("SymbolEncoding")
	State                     = MustCreate("State")
	StateModel                = MustCreate("StateModel")
	Status                    = MustCreate("Status")
	StdCf                     = MustCreate("StdCF")
	StemH                     = MustCreate("StemH")
	StemV                     = MustCreate("StemV")
	StmF                      = MustCreate("StmF")
	StrF                      = MustCreate("StrF")
	StrikeOut                 = MustCreate("StrikeOut")
	StructParent              = MustCreate("StructParent")
	StructParents             = MustCreate("StructParents")
	StructTreeRoot            = MustCreate("StructTreeRoot")
	Style                     = MustCreate("Style")
	SubFilter                 = MustCreate("SubFilter")
	Subj                      = MustCreate("Subj")
	Subject                   = MustCreate("Subject")
	Subtype                   = MustCreate("Subtype")
	Supplement                = MustCreate("Supplement")
	Sv                        = MustCreate("SV")
	Sw                        = MustCreate("SW")
	Sy                        = MustCreate("Sy")
	Synchronous               = MustCreate("Synchronous")
)

// T
var (
	T                         = MustCreate("T")
	Target                    = MustCreate("Target")
	Templates                 = MustCreate("Templates")
	Text                      = MustCreate("Text")
	Threads                   = MustCreate("Threads")
	Thumb                     = MustCreate("Thumb")
	Ti                        = MustCreate("TI")
	TilingType                = MustCreate("TilingType")
	TimeStamp                 = MustCreate("TimeStamp")
	Title                     = MustCreate("Title")
	Tk                        = MustCreate("TK")
	Tm                        = MustCreate("TM")
	Top                       = MustCreate("Top")
	ToUnicode                 = MustCreate("ToUnicode")
	Tr                        = MustCreate("TR")
	Tr2                       = MustCreate("TR2")
	Trapped                   = MustCreate("Trapped")
	Trans                     = MustCreate("Trans")
	Transparency              = MustCreate("Transparency")
	TrapNet                   = MustCreate("TrapNet")
	Tref                      = MustCreate("TRef")
	TrimBox                   = MustCreate("TrimBox")
	TrueType                  = MustCreate("TrueType")
	TrustedMode               = MustCreate("TrustedMode")
	Tu                        = MustCreate("TU")
	Tx                        = MustCreate("Tx")     // Acro form field type for text field.
	Type                      = MustCreate("Type")
	Type0                     = MustCreate("Type0")
	Type1                     = MustCreate("Type1")
	Type1C                    = MustCreate("Type1C")
	Type3                     = MustCreate("Type3")
)

// U
var (
	U                         = MustCreate("U")
	Ue                        = MustCreate("UE")
	Uf                        = MustCreate("UF")
	Underline                 = MustCreate("Underline")
	Unchanged                 = MustCreate("Unchanged")
	Unix                      = MustCreate("Unix")
	Uri                       = MustCreate("URI")
	Url                       = MustCreate("URL")
	Usage                     = MustCreate("Usage")
	UserUnit                  = MustCreate("UserUnit")
)

// V
var (
	V                         = MustCreate("V")
	V2                        = MustCreate("V2")
	VE                        = MustCreate("VE")
	VerisignPpkvs             = MustCreate("VeriSign.PPKVS")
	Version                   = MustCreate("Version")
	Vertices                  = MustCreate("Vertices")
	VerticesPerRow            = MustCreate("VerticesPerRow")
	ViewArea                  = MustCreate("ViewArea")
	ViewClip                  = MustCreate("ViewClip")
	ViewerPreferences         = MustCreate("ViewerPreferences")
	Volume                    = MustCreate("Volume")
	Vp                        = MustCreate("VP")
)

// W
var (
	W                         = MustCreate("W")
	W2                        = MustCreate("W2")
	Watermark                 = MustCreate("Watermark")
	WhitePoint                = MustCreate("WhitePoint")
	Widget                    = MustCreate("Widget")
	Width                     = MustCreate("Width")
	Widths                    = MustCreate("Widths")
	WinAnsiEncoding           = MustCreate("WinAnsiEncoding")
)

// X
var (
	Xfa                       = MustCreate("XFA")
	Xheight                   = MustCreate("XHeight")
	Xml                       = MustCreate("XML")
	Xobject                   = MustCreate("XObject")
	Xref                      = MustCreate("XRef")
	XrefStm                   = MustCreate("XRefStm")
	XStep                     = MustCreate("XStep")
	XYZ                       = MustCreate("XYZ")
)

// Y
var (
	YStep                     = MustCreate("YStep")
	Yes                       = MustCreate("Yes")
)

// Z
var (
	ZapfDingbatsEncoding      = MustCreate("ZapfDingbatsEncoding")
)
